name: classes-and-attributes
main: me.xenotater.classes_and_attributes.Plugin
version: 0.0.1
api-version: 1.20
author: Xenotater
description: A Minecraft plugin that adds RPG classes and special character attributes.
commands:
  classes:
    description: Select or see information about classes
    usage: /<command> [class]
    aliases: [class, cls]
  setclass:
    description: Set your class
    usage: /setclass <class>
    aliases: selectclass
  removeclass:
    description: Remove your class
    usage: /removeclass
    aliases: delclass
  attributes:
    description: Check your attributes or see information about an attribute
    usage: /attributes [attribute]  
    aliases: [attribute, attr]
  addattribute:
    description: add an attribute to someone
    usage: /addattribute <attribute>
    aliases: [addattr]
  removeattribute:
    description: remove an attribute from someone
    usage: /removeattribute <attribute>
    aliases: [delattribute, delattr]
  changediet:
    description: change someones diet
    usage: /changediet <player> <diet>
    aliases: [swapdiet, setdiet]
  setcurse:
    description: give someone a curse
    usage: /setcurse <player> <curse>
    aliases: curse
